-- CREATE DATABASE
CREATE DATABASE HR;

-- USE THE DATABASE
USE HR;

-- CREATION OF PROGRAMMER SEQUENCE
CREATE SEQUENCE PROGRAMMER_COUNT
AS INT
START WITH 1001
INCREMENT BY 1;

-- CREATION OF SOFTWARE SEQUENCE
CREATE SEQUENCE SOFTWARE_COUNT
AS INT
START WITH 2001
INCREMENT BY 1;

-- CREATION OF PROGRAMMER TABLE
CREATE TABLE PROGRAMMER
(
	PROGRAMMER_ID INT PRIMARY KEY DEFAULT (NEXT VALUE FOR PROGRAMMER_COUNT),
	FIRST_NAME VARCHAR(20),
	LAST_NAME VARCHAR(20),
	GENDER VARCHAR(10),
	PHONE VARCHAR(15),
	EMAIL VARCHAR(50),
	DATE_OF_BIRTH DATE,
	DATE_OF_JOIN DATE,
	PROF1 VARCHAR(15),
	PROF2 VARCHAR(15),
	SALARY INT
);

-- CREATION OF SOFTWARE TABLE
CREATE TABLE SOFTWARE
(
	SOFTWARE_ID INT PRIMARY KEY DEFAULT (NEXT VALUE FOR SOFTWARE_COUNT),
	PROGRAMMER_ID INT,
	SOFTWARE_NAME VARCHAR(20),
	DEVELOPED_IN VARCHAR(10),
	COST_PRICE INT,
	SELL_PRICE INT,
	UNITS INT,
	FOREIGN KEY (PROGRAMMER_ID) REFERENCES PROGRAMMER(PROGRAMMER_ID)
);

-- CREATION OF EDUCATION TABLE
CREATE TABLE EDUCATION
(
	PROGRAMMER_ID INT,
	SOFTWARE_ID INT,
	INSTITUTE_NAME VARCHAR(50),
	COURSE_NAME VARCHAR(30),
	COURSE_FEE INT,
	FOREIGN KEY (PROGRAMMER_ID) REFERENCES PROGRAMMER(PROGRAMMER_ID),
	FOREIGN KEY (SOFTWARE_ID) REFERENCES SOFTWARE(SOFTWARE_ID)
);
